# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'panicapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for panicapp

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end

target 'panicapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for panicapp-tvOS

  target 'panicapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
